#!/bin/bash

p_manager="None"
install_curl=false
user=$user
uid=$uid
user_home=$HOME
if command -v curl &> /dev/null
then
	install_curl=true
fi

if command -v apt &> /dev/null
then
	echo "apt is available"
        sudo apt-get install zsh -y
	if install_curl
	then
		echo Installing curl
		sudo apt-get install curl -y
	fi
elif command -v dnf &> /dev/null
	then
	    echo "dnf is available"
	    p_manager="dnf"
	elif command -v yum &> /dev/null
	sudo dnf install zsh -y
	if install_curl
	then
		echo Installing curl
		sudo dnf install curl -y
	fi
then
	echo "yum is available"
	sudo yum install zsh -y
	if install_curl
	then
		echo Installing curl
		sudo yum install curl -y
	fi
elif command -v pacman &> /dev/null
then
	echo "pacman is available"
	sudo pacman -S zsh --noconfirm
	if install_curl
	then
	echo Installing curl
		sudo pacman -S curl --noconfirm
	fi
else
    echo "No known package manager found"
fi

sudo sed -i "s:$user\:x\:$uid\:$uid\:$user\:$user_home\:/bin/bash:$user\:x\:$uid\:$uid\:$user\:$user_home\:/bin/zsh:" /etc/passwd

curl -o $HOME/.p10k.zsh "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.p10k.zsh"

curl -o $HOME/.zcompdump "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.zcompdump"

curl -o $HOME/.zshrc "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.zshrc"

source $HOME/.zshrc
