#!/bin/bash

p_manager="None"
install_curl=false
if command -v curl &> /dev/null
then
	install_curl=true
fi

if command -v apt &> /dev/null
then
    echo "apt is available"
    p_manager="apt"
elif command -v dnf &> /dev/null
then
    echo "dnf is available"
    p_manager="dnf"
elif command -v yum &> /dev/null
then
    echo "yum is available"
    p_manager="yum"
elif command -v pacman &> /dev/null
then
    echo "pacman is available"
    p_manager="pacman"
elif command -v zypper &> /dev/null
then
    echo "zypper is available"
    p_manager="zypper"
else
    echo "No known package manager found"
fi

case p_manager in 
	"apt")
		sudo apt-get install zsh -y
		if install_curl
		then
			echo Installing curl
			sudo apt-get install curl -y
		fi
		;;
	"dnf")
		sudo dnf install zsh -y
		if install_curl
		then
			echo Installing curl
			sudo dnf install curl -y
		fi
		;;

	"yum")
		sudo yum install zsh -y
		if install_curl
		then
			echo Installing curl
			sudo yum install curl -y
		fi
		;;

	"pacman")
		sudo pacman -S zsh --noconfirm
		if install_curl
		then
			echo Installing curl
			sudo pacman -S curl --noconfirm
		fi
		;;	

	"zypper")
		sudo zypper install zsh
		if install_curl
		then
			echo Installing curl
			sudo zypper install curl
		fi
		;;


chsh $(whoami) -s $(which zsh)

curl -o $HOME/.p10k.zsh "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.p10k.zsh"

curl -o $HOME/.zcompdump "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.zcompdump"

curl -o $HOME/.zshrc "https://raw.githubusercontent.com/farukerdem34/zsh-conf/master/.zshrc"

source $HOME/.zshrc
