#!/bin/zsh
cp $HOME/.zshrc .
cp $HOME/.p10k.zsh .
cp $HOME/.tmux.conf .
cp $HOME/.vimrc .
cp $HOME/.zcompdump .
cp -r $HOME/.config/kitty .config/kitty
cp $HOME/.config/fastfetch/config.jsonc .config/fastfetch/config.jsonc
